--liquibase formatted-sql
--changeset pavel:init tables


create table users
(
    id       bigint generated by default as identity,
    login    text        not null unique,
    password text        not null,
    role     varchar(10) not null check (role in ('TEACHER', 'STUDENT')),
    primary key (id)
);

create table tests
(
    id              text not null,
    created_at      timestamptz,
    description     text,
    name            text not null,
    need_to_answer  integer,
    questionCount   integer,
    show_result     text check (show_result in ('MISTAKES_AND_CORRECTS', 'ONLY_MISTAKES', 'ONLY_SCORE', 'NOTHING')),
    creation_status text check (creation_status in
                                ('FILLING_BASE_ATTRIBUTES', 'QUESTION_FILLING', 'FILLING_SETTINGS', 'CREATED')),
    created_by      bigint references users(id),
    primary key (id)
);

create table questions
(
    id      bigint generated by default as identity,
    text    text not null,
    test_id text not null references tests(id),
    primary key (id)
);

create table answers
(
    id          bigint generated by default as identity,
    is_correct  boolean not null,
    text        text    not null,
    question_id bigint  not null references questions(id),
    primary key (id)
);

create table test_attempts
(
    id           bigint generated by default as identity,
    completed_at timestamptz,
    is_success   boolean,
    score        bigint,
    started_at   timestamptz,
    test_id      text   not null references tests(id),
    user_id      bigint not null references users(id),
    primary key (id)
);

create table user_answers
(
    id                 bigint generated by default as identity,
    is_correct         boolean,
    attempt_id         bigint not null references test_attempts(id),
    question_id        bigint not null references questions(id),
    selected_answer_id bigint references answers(id),
    primary key (id)
);

create table authentication_attempts
(
    id           bigint generated by default as identity,
    attempts     integer     not null,
    last_attempt timestamptz not null,
    login        text        not null,
    primary key (id)
);
